### ISSUE TITLE
Please add additional packages

### ISSUE THREAD

**Issue by phoerious** [bugzy/keepassxc-rpm-spec#6]
I migrated our Docker build environment from Ubuntu 14.04 to CentOS 7.4 and wanted to ask you if you could add a few more packages to your EPEL, so I don't need to add too many other repositories of which I don't know if they are maintained.

The packages needed are:

- cmake (Version 3.1 or higher)
- libyubikey-devel (1.13 or higher)
- libykpers-devel (1.18.0 or higher)

cmake would be the most important of the three packages, as the other two are quite small and also optional dependencies.

**Comment by bugzy** [comment]
These packages exist in the centos 7 EPEL repos as:
- cmake3 (3.6.3) -- EPEL repo
- libyubikey-devel (1.13)
- ykpers-devel (1.18.0)
so there is no need to add them here, but thanks for the heads up. (Note: the centos 7 packages have been built with the above since release 2.1.0)
If this resolves your concern I will close the issue; otherwise, let me know what other problems exist.

**Comment by phoerious** [comment]
That's good to know and reduces the number of required external repositories to only yours. The YubiKey libs also seem to be recent, which is required for them to work inside an AppImage.
I had apprehensions that using EPEL would pull in newer versions of other packages, which would then be unsuitable for building AppImages, but I see that this is not the case.
